# Generated by Django 2.1.7 on 2019-03-13 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county', models.CharField(max_length=120)),
                ('doc_type', models.CharField(max_length=120)),
            ],
        ),
    ]
