# Generated by Django 2.1.7 on 2019-04-16 15:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0002_auto_20190319_1235'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recording_date', models.TextField()),
                ('doc_title', models.TextField()),
                ('involved', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='DateRange',
        ),
        migrations.DeleteModel(
            name='DocType',
        ),
        migrations.RemoveField(
            model_name='county',
            name='county',
        ),
        migrations.AddField(
            model_name='county',
            name='models',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='county',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=120),
            preserve_default=False,
        ),
    ]
