# Generated by Django 2.1.7 on 2019-04-17 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0003_auto_20190416_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lien',
            name='recording_date',
            field=models.CharField(max_length=120),
        ),
    ]
